### ISSUE TITLE
Delay before screen lock

### ISSUE THREAD

**Issue by erfanio** [google/xsecurelock#12]
I'd be nice to have a few seconds (configurable) after the screen saver is activated to move the mouse or click something to prevent the screen getting locked.
Or something even fancier would be fading out the screen so you know the screen saver is going to get activated.

**Comment by divVerent** [comment]
On Apr 20, 2017 05:42, "Erfan" <notifications@github.com> wrote:

I'd be nice to have a few seconds (configurable) after the screen saver is
activated to move the mouse or click something to prevent the screen
getting locked.
Or something even fancier would be fading out the screen so you know the
screen saver is going to get activated.


Fading is probably out of scope, as there's too many ways in which this can
go wrong.

A simple timer that allows unlocking right after xsecurelock was started -
preferably optional so it is used only when xss-lock or similar started
xsecurelock, but not when you manually lock the screen - sounds like a good
idea though and can be done without compromising security.

Could also do it "halfway fancy" and use a different background color than
black while the screen is not "really" locked yet. Will see.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/xsecurelock/issues/12>, or mute the thread

**Comment by divVerent** [comment]
Can you try this branch?

**Comment by erfanio** [comment]
Yeh looks good
I really like the animation it looks dope 💯

**Comment by erfanio** [comment]
This currently breaks when going to suspend in my setup. xss-lock invokes xsecurelock right before going to sleep so it never finishes its (unauthorised wake) timeout, and when it wakes up you can just move the mouse and unlocked!

my xss-lock command

```
XSECURELOCK_ALLOW_UNAUTHENTICATED_WAKEUP_TIME_SEC=10 xss-lock -- xsecurelock auth_pam_x11 saver_blank
```

do you have a recommendation for a xss-lock replacement?

**Comment by erfanio** [comment]
To anyone who is having the same problem I suggest using the `-n` flag in xss-lock.

https://gist.github.com/erfanio/eec67e1a538eeef3ff72562412030b6a

**Comment by divVerent** [comment]
Good catch. I'll see how to avoid the animation when using xss-lock.

**Comment by divVerent** [comment]
Fixed this "security hole" now (not necessarily one in XSecureLock as xss-lock usage was not documented or tested yet) by:

- Detect suspend while XSecureLock was running using a simple timer: a179a019c3f600b5cd013c2f2f2626cdf72cd964
- Detect xss-lock without -l option and disable unauthenticated wakeup in that case: 97128c169cb43ba0f7fdb09fc6b61f7fe78386fd
- Detect xss-lock with -l option and properly close the file descriptor when the lock is armed: 97128c169cb43ba0f7fdb09fc6b61f7fe78386fd

Also, documenting now how to use xss-lock with XSecureLock properly

**Comment by divVerent** [comment]
Hm... can this even be done right? I am close to removing this support again as it seems to be impossible to do right.

- xss-lock -l doesn't always pass the FD (it does when it is inhibiting a suspend, but not when we're launched by a X11 screen saver timeout).
- Even if we get the FD, xss-lock can't distinguish us releasing the FD because we're exiting from releasing the FD because we're armed.
- End result: the machine will suspend anyway, even if we try to cancel the lock.

**Comment by divVerent** [comment]
Yes, I've decided to undo the unauthenticated wakeup feature. It's not gonna work reliably anyway with xss-lock, so we may as well rather support it the "xss-lock -n" way.

**Comment by erfanio** [comment]
@divVerent I appreciate the effort, I understand xss-lock is very difficult to work with.

I think it would help if you added a wiki to your repo so you can have "recommended" ways to launch xsecurelock.

**Comment by schachmat** [comment]
xsecurelock now has two tools "dimmer" and "until_nonidle" that can be used to dim the screen before locking. See https://github.com/google/xsecurelock#possible-other-tools for more information.
