### ISSUE TITLE
When unlocking first key press in ignored

### ISSUE THREAD

**Issue by erfanio** [google/xsecurelock#14]
I'm using `saver_blank` with `auth_pam_x11` and when the screen is off and I start typing my password the first key press is ignored which results in my password being wrong.
It would be great if the first key press (which causes the screen to wake up and go to the lock screen) was not ignored.

**Comment by scriptum** [comment]
Unfortunately [this is by design](https://github.com/google/xsecurelock/blob/master/auth_child.c#L110).

**Comment by divVerent** [comment]
Doesn't mean it can't be changed. Can always become an option. Will see
about that.

**Comment by bhajneet** [comment]
Another option is to mentally change your password. Add any key to the beginning in your head. An option in the future is nice too.

**Comment by erfanio** [comment]
@bhajneet ... and then all the other places I have to enter my password are gonna be wrong

**Comment by divVerent** [comment]
So, the real reason why I did it this way was that on some systems, what I need to enter depends on the prompt. Also it's an obvious security mistake to start entering the password before seeing a prompt (e.g. what if the screen lock wasn't even active in the first place and some JavaScript is registering your keypresses).

However, this is mainly because I'm using saver_blank. When using a personalized screen saver or at least xscreensaver, and the monitor therefore stays on, you may have sufficient information to start typing your password (assuming you're not running any untrusted code that could get at your password by other means, e.g. faking a login screen, anyway).

So it seems like I'll make this a runtime option.
