### ISSUE TITLE
intezer report parts of xsecurelock as malware. 

### ISSUE THREAD

**Issue by opentokix** [google/xsecurelock#140]
This file: /usr/local/libexec/xsecurelock/saver_multiplex

GNU C17 9.3.0 -mtune=generic -march=x86-64 -g -O2 -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection
Malware
Generic Malware

**Comment by divVerent** [comment]
Given the path name, you likely compiled it yourself, so I would recommend
doing an audit of the source code for possible malware, as well as checking
out the compiler for possible malware in there. A good start should be
booting from a clean live image and copying off the xsecurelock source,
binaries and the compiler binaries from there and comparing them to clean
versions.

This specific binary talks to X11 to watch over the screen size, manages
one subwindow per screen, and maintains child processes to draw a screen
saver on each.

I would bet this report is a false positive maybe caused by
saver_multiplex's logic to keep its child processes alive by restarting
them if they exit - something normally only programs like init and systemd
do.

There is however nothing we can do about that; one you have done the above
verification, contacting Intezer may help.

Another thing you can try is different compiler flags - false positive
reports are often "tickled" by minor changes such as optimization flags,
compiler versions or similar. May also want to try compiling with clang.

**Comment by divVerent** [comment]
Virustotal report of the binary I have: https://www.virustotal.com/gui/file/a30746114b7dbf213ccbdc46628564935af55b4fecfc0b30350367dc0b4f8447?nocache=1

Note that checksum will likely differ from yours due to different compiler version or settings. This is expected.
