### ISSUE TITLE
Support user-level customisations

### ISSUE THREAD

**Issue by soumya92** [google/xsecurelock#35]
On a multi-user system, it's not reasonable to ask users to just install global saver_* or auth_* modules in /usr or similar. There needs to be a way for a user to customise xsecurelock without needing write access to global locations.

I can think of a few ways to do this:
- Provide a `saver_user`/`auth_user` that uses an env var to determine which saver to execute out of the user's home directory
- In addition to whitelisting the /usr path, also whitelist a per-user path (~/.config/xsecurelock or something).
- Drop the whitelist entirely. I'm not sure the whitelist is necessary. If someone wants to bypass the whitelist, they can just compile their own binary and run it out of their home directory anyway.

There may be other ways to do this as well. But whatever the solution, I'd greatly appreciate the ability for users to specify auth/saver modules that reside in their home folder.

**Comment by schachmat** [comment]
I see and you are correct. I was confused, because I use a custom saver_ module that lives in another directory just fine. In my case that works because I still use the saver_multiplex as the global saver and the whitelist check is only done against the global saver, not the per-screen savers. I don't see an immediate reason for not using saver_multiplex and one could argue that users should not be able to pick their own auth modules, because they may make their system un-unlockable, but well, we can't fix users anyway, so I'm not sure if this whitelisting is still needed. divVerent, what do you think?

**Comment by divVerent** [comment]
Actually, the main reason for the whitelist is safe command-line parsing - I did not want users to be able to launch the auth module as a saver module or vice versa as this would "mostly work" except be horribly insecure.

But indeed, we could relax it by only requiring the _basename_ of the path to start with auth_ or saver_.

**Comment by schachmat** [comment]
Whitelisting based on the basename sounds very reasonable. Let's go with it.

**Comment by divVerent** [comment]
And also... yes, the logic was missing in saver_multiplex. Added this now too.
