### ISSUE TITLE
Notifications is shown over auth screen

### ISSUE THREAD

**Issue by arcan1s** [google/xsecurelock#6]
Hi,

When an auth screen is activated notifications (at least skype and kde notifications) are shown over this screen. `auth_pam_x11` and `auth_pamtester` modules are affected.

Is it possible to paint auth screen on the foreground?

**Comment by corpix** [comment]
I have similar problems with [dunst][dunst-link] on Archlinux. I am using xsecurelock https://github.com/google/xsecurelock/commit/b6f1476c2317f2734f0f31218df0dcfd91863794 built from git.

[dunst-link]: https://github.com/knopwob/dunst

**Comment by divVerent** [comment]
Thank you, this can prove quite helpful especially as dunst is well configurable.

Can you provide the following information:

- Your dunst configuration file (possibly shortened but still causing the issue)
- The window manager and compositor you are using

I think with this information I should be finally able to reproduce and fix it. I actually already have an idea how to do this, however it depends on knowing whether there is a compositor or not and thus may need a command-line flag.

**Comment by corpix** [comment]
My apologies for late answer.

There are my configs:
  - [dunst 1.1.0-1][dunst-config]
  - [compton 0.1_beta2-5][compton-config] compositor. Command-line to run it `/usr/bin/compton -b --config /home/corpix/.compton.conf`

Also I am using openbox window manager. I could show configuration file, but don't see the point to do this because I have changed some key bindings only, leaving other things default. I will attach it if more information will be required.

[dunst-config]: https://gist.github.com/corpix/6fb278fa380363ed402c
[compton-config]: https://gist.github.com/corpix/3c4cd3fbd0f11aadf39e

**Comment by divVerent** [comment]
Pushed an attempt at using the composite overlay window to a branch called "xcomposite". Can you try this?

Even with your configs, I can't reproduce the issue - however, I did notice that with your compton config, the screen "fades out" at startup of the screen saver, which does worry me as it shows there are chances  the compositor can make the screen saver transparent. Using the composite overlay window fixes that part.

**Comment by corpix** [comment]
Thanks for you work, but I have moved to gnome-shell for a while, not sure I could try it soon, sorry.

**Comment by divVerent** [comment]
I pushed the changes to use the XComposite overlay window to master. Seems to work fine and, as said, I can observe that there is no fading out effects or anything similar that may make anything shine through while the screen saver is running. So I assume this covers notifications too.

Considering this solved now.

**Comment by coffebar** [comment]
I have this issue on i3 with xcompmgr compositor.
