### ISSUE TITLE
Not drawing while X display is not in foreground

### ISSUE THREAD

**Issue by Vladimir-csp** [google/xsecurelock#68]
This is not a problem with xsecurelock, but rather a way X behaves. If something happens while X display is in background (different VT), changes will be visible only after some delay when switching back. 

If locker is initiated on a background VT (e.g. `loginctl lock-sessions` while multiple sessions are running with `xss-lock -- xsecurelock`), switching to a locked session will show unlocked screen content for some time.

If there exists a way to force X to update its buffer while in background, it better be utilized.

**Comment by divVerent** [comment]
Probably nothing we can do about this - but good edge case.

I remember that switching VTs even with a crashed X server may retain old screen content on some GPUs. Like, even if you switch to a text terminal, kill -9 the X server (without anything spawning a new one) and then Ctrl-Alt-F7 would show old content. This is because video RAM for text modes and graphics modes is in different memory areas, and the mode switch thus makes the previously stored content visible. Even less xsecurelock can do about (one could however think about making X.org itself clear the frame buffer on VT switch; note that it's not as easy as it sounds as OpenGL applications expect some video RAM to remain e.g. for textures, so this would really have to be specific to the frame buffer).

I also know no way to detect this situation from an X11 application so we don't close the inhibit file descriptor in that case; however this wouldn't help much anyway as usually inhibits time out after like 5 seconds anyway (`InhibitDelayMaxSec` in `/etc/systemd/logind.conf`).
