### ISSUE TITLE
XSECURELOCK_BLANK_TIMEOUT affects auth screen.

### ISSUE THREAD

**Issue by evolarium** [google/xsecurelock#75]
I have the following configuration for xsecurelock:

XSECURELOCK_FONT=Arimo
XSECURELOCK_BLANK_DPMS_STATE=suspend
XSECURELOCK_BLANK_TIMEOUT=0

In version 1.1 this works fine.  In newer versions, when I try to unlock, the screen immediately suspends based on the timeout set in XSECURELOCK_BLANK_TIMEOUT.  I have bisected it, and this behaviour first shows up in commit c0aab254c828434d9b82fde099eead4c7ae39c5f.

**Comment by divVerent** [comment]
That this feature might do that with a zero blanking timeout is not a
surprise - we intentionally are now keeping the saver alive so we can show
auth in a window.

The problem is that blanking uses the same mechanism.

I had also introduced a signal SIGUSR1 we send to the saver when the auth
dialog is exited. This was normally good enough to reset everything - but
with short blanking timeouts it isn't, as blanking while the auth window is
shown is still too likely.

I think what this means is that screen blanking needs to be revisited
entirely. Maybe even should be moved from saver_blank to the main process.
Will see.

**Comment by divVerent** [comment]
Moving blanking to the main process shouldn't be particularly hard given it already knows about the relevant mouse or keyboard events, BTW. The only part I dislike is that it'd add something in there that cannot ever be event based, so it'll "cement" the current state that we have to wake up xsecurelock in regular intervals.

(Currently done as a defense in depth to reacquire grabs if lost for whatever reason, but that shouldn't happen anymore, and to force the mouse cursor to go away if a buggy saver enabled it)

**Comment by divVerent** [comment]
Have created a first implementation but didn't test it yet (am on a Chromebook, blanking can be called but does nothing).

**Comment by evolarium** [comment]
I've tried it and it currently has the original behaviour for me.  I don't know if there's a better approach, but if I make the following change, I get the behaviour I expect.  (Auth screen stays active for XSECURELOCK_AUTH_TIMEOUT seconds, screen will blank XSECURELOCK_BLANK_TIMEOUT seconds after auth screen finished).

[blanking patch](https://github.com/google/xsecurelock/files/3213705/blanking.txt)

**Comment by divVerent** [comment]
About that not sure - what I'd find weird is that this will be confusing
given the DPMS timers (xset dpms) can also kick in during auth.

But yes, let's keep this open to decide it for real. Either we should
support this use case by setting blank timeout to 0, or we should have a
separate way to blank instead of saving

**Comment by divVerent** [comment]
Even with your change, I can't get a timeout value of 0 to work; it then unblanks when releasing the enter key from starting xsecurelock, and never blanks again. I tried various ways to detect that but none worked properly, they very often had the race condition that the keypress to wake up xsecurelock is handled but the screen is immediately blanked again.

Still, I took your patch and added some cleanup (making it not depend on mapping status but - better, as auth helpers do not _have_ to map their window - on the child process status).

But for now I gave up on re-blanking after key release events. Maybe can do a hack, but responding to the Xss notification seems infeasible.

**Comment by divVerent** [comment]
For now added a hack that solves this for me; too bad we can't do this in the Xss notification as it seems there's a race condition with them (we first get the Xss event, then the key event, so while handling the Xss event, we'd think we should stay blanked, but the key event wakes us up for real, and for some reason trying to blank and unblank in quick succession does not always yield the last requested state).
