### ISSUE TITLE
Sometimes shows underlying screen

### ISSUE THREAD

**Issue by waptaff** [google/xsecurelock#80]
Installed `xsecurelock` from github, at commit fc16012578d8631e92a1320ad2ae671900e4b360.

Very disappointed that sometimes, the underlying screens are shown under the auth dialog.  See:

![xsecurelock](https://user-images.githubusercontent.com/6563434/58433533-c2e05c00-8085-11e9-80fc-2ac58fa975e4.jpg)

I have a 3-monitor setup, with one rotated 90°, all on same same intel integrated chipset, controlled with `xrandr`, under Debian.

I run `xsecurelock` without any parameter nor xsecurelock-specific environment variable.

I could not find a pattern to reproduce, unfortunately; I lock/unlock my workstation about ten times in a day and this nasty situation happens about once a day.

**Comment by divVerent** [comment]
This is typical for use with an incompatible compositor. What's most odd is that the obscurer window should prevent precisely this, even with a bad compositor.

What desktop environment and compositor are you using?

Can the screen behind this be interacted with? Does it update (when e.g. a ping is running in the terminal)?

As a stopgap, you can set `XSECURELOCK_NO_COMPOSITE=1`, but then you can get another issue: because the whole issue is the method of overriding transparency a compositor may use - which in turn causes issues like yours when the running compositor is in some ways "weird".

**Comment by waptaff** [comment]
I'm using AwesomeWM, which AFAIK has no compositor.

The screen behind cannot be interacted with, and it does not update.

Trying to set `XSECURELOCK_NO_COMPOSITE=1`, I'll see if it changes anything.

Thanks for your support,

**Comment by divVerent** [comment]
That the screen behind does not update is interesting and this means I may
have a workaround.

Normally I just create a window with CWBackPixel set to black - this should
be enough to draw the screen in black.

I may try adding explicit code to draw a black rectangle just in case. By
spec this should not be needed, but graphics driver bugs happen.

Also, given this info, I would suggest trying saver_xscreensaver. I.e. just
install the xscreensaver package and use
XSECURELOCK_SAVER=saver_xscreensaver to select it. As it actively draws
over its window every frame, it should help with the bug too.

**Comment by waptaff** [comment]
Setting `XSECURELOCK_NO_COMPOSITE=1` didn't change the behavior: _sometimes_ I get the underlying screen, not updating.

Willing to try a “black rectangle” patch.

Spawning `xscreensaver` in the background works, but is a bit absurd!

**Comment by divVerent** [comment]
That `XSECURELOCK_NO_COMPOSITE=1` changed nothing is odd, but may explain something.

Please recompile but explicitly pass `--with-xcomposite` to `./configure`. You may have to install a library first to make this work (`libxcomposite-dev` on Debian).

Very likely this should at the very least make the same bug show a fully white glaring background rather than the old screen content.

As for more explicitly blacking out the screen, I'll work on that later and make a patch for you to try.

**Comment by divVerent** [comment]
Try this commit. If this does help, I'd like to narrow it down to less changes, as this call can be expensive and cause flicker.

**Comment by waptaff** [comment]
Ok, I checked out, compiled and installed the `divVerent/explicitly-clear-background-window` branch, and the issue didn't reappear after two full days of usage — that's a very good sign, as normally it would've happened by now.
