### ISSUE TITLE
Add transparency support to prompt/auth dialog

### ISSUE THREAD

**Issue by SevereOverfl0w** [google/xsecurelock#88]
It would be visually pleasing to be able to have a blended background to the prompt, and especially when using the mpv saver, see some of the movement behind.

**Comment by divVerent** [comment]
As they're on different windows owned by different processes, this is rather infeasible.

**Comment by SevereOverfl0w** [comment]
Can't transparency be set on a window when using a compositor?

**Comment by divVerent** [comment]
Yes, but xsecurelock strongly circumvents (even actively breaks) compositors specifically so transparent windows cannot be on top of the screen lock.

Yes, this is unfortunate. But there simply is no other way to prevent compositors from rendering a transparent notification window on top of a screen lock.

**Comment by divVerent** [comment]
As an example of what can happen if a screen lock does not break compositors - `compton -i 0.9` (rendering inactive windows with transparency, a seemingly harmless feature) breaks xscreensaver by letting other windows shine through the screen lock window.

Why? Because screen lock windows tend to be OverrideRedirect and seen as inactive.

And of course the whole issue with transparent notifications - a notification window does not cause any VisibilityNotify to a window below it if it is transparent, so a screen locker cannot counteract them.

So xsecurelock's approach is to acquire access to the compositor's window and to create its own windows on top of that - then with most compositors, whatever the compositor does is overlayed by the screen lock and thus harmless. This works with most but not all compositors:

- Some compositors draw on the composite overlay window with the `IncludeInferiors` drawing mode. These will then draw on top of xsecurelock. A well-known example is `compton --backend xrender --paint-on-overlay`.

- Some compositors hide their window when a fullscreen window is on top. This is why we have the obscurer window - it only _almost_ covers the entire screen, preventing compositors from detecting the fullscreen situation and unredirecting (also, in case of a failure, this window obscures the otherwise interesting content).

- Some compositors just draw on the root window (e.g. older versions of compton without `--paint-on-overlay`). These should generally get overlapped by xsecurelock, however nvidia drivers once had a bug preventing that from working.

**Comment by SevereOverfl0w** [comment]
I see, so short of writing your own compositor to support this, this is very difficult.
